/-
  Basic module — imports definitions for the impossibility theorem.
-/
import DASHImpossibility.Defs
import DASHImpossibility.Trilemma
import DASHImpossibility.Iterative
import DASHImpossibility.Lasso
import DASHImpossibility.NeuralNet
import DASHImpossibility.SplitGap
import DASHImpossibility.SymmetryDerive
import DASHImpossibility.Ratio
import DASHImpossibility.General
import DASHImpossibility.SpearmanDef
import DASHImpossibility.Impossibility
import DASHImpossibility.Corollary
import DASHImpossibility.DesignSpace
import DASHImpossibility.FlipRate
import DASHImpossibility.ModelSelection
import DASHImpossibility.AlphaFaithful
import DASHImpossibility.UnfaithfulBound
import DASHImpossibility.RashomonUniversality
import DASHImpossibility.LocalGlobal
import DASHImpossibility.ConditionalImpossibility
import DASHImpossibility.SymmetricBayes
import DASHImpossibility.Efficiency
